CSCI-GA-2820-SP24-003/wishlists

service/routes.py
tests/test_routes.py
tests/test_wishlist.py

Made the following changes:
- Added update_wishlist endpoint in `routes.py`
- Added test cases for update wishlist in `test_routes.py` and `test_wishlists.py`

Added update wishlist endpoints

---

service/routes.py
tests/test_routes.py

This PR contains - 
- Implementation for delete wishlist endpoint (routes.py)
- Test cases for delete wishlist endpoint (test_routes.py)

Feature : Delete Wishlist #12

---

service/routes.py
tests/test_routes.py

- Endpoint for listing wishlists
- Tests for endpoint

List Wishlists

---

tests/test_routes.py

Removed the duplicate function `_create_wishlist` in `tests/test_routes.py`.

Fixed the bug

---

service/models/__init__.py
service/models/wishlist.py
service/models/wishlist_item.py
tests/factories.py
tests/test_wishlist.py
tests/test_wishlist_item.py

Made the following changes
- Added WishlistItem model
- Added relationship to Wishlist model
- Added code to check wishlist_items to read test
- Added test cases for WishlistItem model

added WishlistItem model

---

service/models/wishlist.py
service/models/wishlist_item.py
service/routes.py
tests/factories.py
tests/test_routes.py
tests/test_wishlist.py
tests/test_wishlist_item.py

- Ability to add an item to an existing Wishlist
- Test case for adding item to wishlist
- Some changes due to Python formatting (autoformat on save)

Add Item to Wishlist

---

service/routes.py
tests/factories.py
tests/test_routes.py
tests/test_wishlist_item.py

This PR contains -
- Implementation for read item endpoint
- Test cases for read wishlist endpoint

Read wishlist item API call

---

service/models/wishlist_item.py
service/routes.py
tests/test_routes.py
tests/test_wishlist_item.py

- Ability to list the items of a wishlist using `GET /wishlists/<id>/items`
- Test cases for new route

List Wishlist Items

---

service/models/wishlist.py
tests/test_routes.py
tests/test_wishlist.py

- Fixed a bug in deserialization of items from wishlist
- Testcases added for wishlist serialize and deserialize
- Modified wishlist testcases to make it consistent with sample-accounts repo - sad paths included
- Added negative testcases for error_handlers.py file
- Increased code coverage from 87% to 96.21%

Increasing code coverage from 87% to 96%

---

service/routes.py
tests/test_routes.py
tests/test_wishlist.py
tests/test_wishlist_item.py

Made the Following changes:-
- added delete wishlist items
- added delete wishlist item route test case
- added delete wish item model test case
- change deserialize wish item key and type error into wishlist item test file 
- get_addresses and list_addresses function name changed to  get_wishlist_item & list_wishlist_items added WishListItem  clean up to test_routes

added delete wishlist items

---

service/routes.py
tests/test_routes.py
tests/test_wishlist.py

Added the read wishlist items and changed files include test_wishlists.py, test_routes.py, and routes.py.
Ran all tests and they came back succesfully.

Added read wishlist and test cases

---

README.md
service/routes.py
tests/test_routes.py
tests/test_wishlist.py
tests/test_wishlist_item.py

This PR makes following updates:
- Added `update_items` in `service/routes.py`
- Added test cases in `tests/test_routes.py`
- Added test cases in `tests/test_wishlist_item.py`

Update wishlist items

---

service/routes.py
tests/test_routes.py

This PR contains - 
- code to add action route for making wishlist publicly visible
- testcases

Action route endpoint to publish wishlist

---

service/routes.py
tests/test_routes.py

I created a route to unpublish a wishlist (i.e. reverse publish a wishlist)

Added route to unpublish wishlist

---

service/routes.py
tests/test_routes.py

Added case for handling multiple wishlist with same name for the user. Changed corresponding test case as well

Added duplicate creation check and updated test case

---

dockerfile
k8s/deployment.yaml
k8s/ingress.yaml
k8s/postgres.yaml
k8s/pv.yaml
k8s/secret.yaml
k8s/service.yaml

Applied changes for two stories the kub setup as well as the postgres db setup

Added setup for kub and changed accordingly for postgres

---

service/routes.py
tests/test_routes.py

Changes for adding health endpoint

health check added

---

.devcontainer/docker-compose.yml
.github/workflows/bdd.yml
features/environment.py
features/steps/web_steps.py
features/steps/wishlists_steps.py
features/wishlists.feature
wsgi.py

This PR makes the following updates
* Update `environment.py` to use `firefox` driver
* updated steps inside `web_steps.py`
* updated `wishlists_steps.py`
* updated `wishlist.feature`

Bdd UI for create

---

.tekton/pipeline.yaml

added bdd pipeline

---

.tekton/pipeline.yaml

Found a minor bug in config corrected it.

Added changes for bdd pipeline

---

Dockerfile

Needed to change the python slim image location

Needed to change the python slim image location
